// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//! DDL-shape checks for [`migrate`](crate::migrate): the three dialect
//! spellings, defaults, `REFERENCES`, the add-column diff and idempotency.

use super::*;
use crate::migrate;

const ARTICLE_SQLITE: &str = "CREATE TABLE IF NOT EXISTS articles \
    (id INTEGER PRIMARY KEY AUTOINCREMENT, author_id INTEGER NOT NULL REFERENCES authors (id), \
     deleted INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL DEFAULT 0)";
const ARTICLE_POSTGRES: &str = "CREATE TABLE IF NOT EXISTS articles \
    (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
     author_id BIGINT NOT NULL REFERENCES authors (id), deleted BOOLEAN NOT NULL DEFAULT false, \
     created BIGINT NOT NULL DEFAULT 0)";
const ARTICLE_MYSQL: &str = "CREATE TABLE IF NOT EXISTS articles \
    (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, \
     author_id BIGINT NOT NULL REFERENCES authors (id), deleted BOOLEAN NOT NULL DEFAULT 0, \
     created BIGINT NOT NULL DEFAULT 0)";

#[tokio::test]
async fn create_table_renders_the_three_dialects() {
    let cases = [
        (Dialect::Sqlite, ARTICLE_SQLITE),
        (Dialect::Postgres, ARTICLE_POSTGRES),
        (Dialect::Mysql, ARTICLE_MYSQL),
    ];
    for (dialect, expected) in cases {
        let db = Mock::with_dialect(dialect);
        migrate::create_table::<Article, _>(&db).await.unwrap();
        let (sql, params) = db.calls().remove(0);
        assert_eq!(sql, expected, "dialect {dialect:?}");
        assert!(params.is_empty());
    }
}

#[tokio::test]
async fn non_auto_pk_and_boolean_defaults_render_per_dialect() {
    let db = Mock::with_dialect(Dialect::Sqlite);
    migrate::create_table::<Setting, _>(&db).await.unwrap();
    assert_eq!(
        db.calls().remove(0).0,
        "CREATE TABLE IF NOT EXISTS settings \
         (name TEXT NOT NULL PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1)"
    );

    let db = Mock::with_dialect(Dialect::Postgres);
    migrate::create_table::<Setting, _>(&db).await.unwrap();
    assert_eq!(
        db.calls().remove(0).0,
        "CREATE TABLE IF NOT EXISTS settings \
         (name TEXT NOT NULL PRIMARY KEY, enabled BOOLEAN NOT NULL DEFAULT true)"
    );
}

#[tokio::test]
async fn empty_columns_is_an_error_naming_the_model() {
    let db = Mock::with_dialect(Dialect::Sqlite);
    let err = migrate::create_table::<Plain, _>(&db).await.unwrap_err();
    let message = err.to_string();
    assert!(message.contains("plain") && message.contains("columns()"), "got: {message}");
    assert!(db.calls().is_empty());
}

#[tokio::test]
async fn a_db_without_a_dialect_is_an_error() {
    let db = Mock::default();
    let err = migrate::create_table::<Article, _>(&db).await.unwrap_err();
    assert!(err.to_string().contains("does not report a dialect"));
    assert!(db.calls().is_empty());
}

#[tokio::test]
async fn add_missing_columns_alters_only_the_missing_ones() {
    let db = Mock {
        dialect: Some(Dialect::Sqlite),
        rows: vec![
            row_of(&[("name", serde_json::json!("id"))]),
            row_of(&[("name", serde_json::json!("deleted"))]),
        ],
        ..Mock::default()
    };

    assert_eq!(migrate::add_missing_columns::<Article, _>(&db).await.unwrap(), 2);
    let calls = db.calls();
    assert_eq!(calls.len(), 3);
    assert_eq!(calls[0].0, "PRAGMA table_info(articles)");
    assert!(calls[0].1.is_empty());
    assert_eq!(
        calls[1].0,
        "ALTER TABLE articles ADD COLUMN author_id INTEGER NOT NULL REFERENCES authors (id)"
    );
    assert_eq!(calls[2].0, "ALTER TABLE articles ADD COLUMN created INTEGER NOT NULL DEFAULT 0");
}

#[tokio::test]
async fn sync_creates_then_adds_and_a_second_run_adds_nothing() {
    let all_columns: Vec<Row> = ["id", "author_id", "deleted", "created"]
        .iter()
        .map(|name| row_of(&[("name", serde_json::json!(name))]))
        .collect();
    let db = Mock { dialect: Some(Dialect::Sqlite), rows: all_columns, ..Mock::default() };

    assert_eq!(migrate::sync::<Article, _>(&db).await.unwrap(), 0);
    let calls = db.calls();
    assert_eq!(calls.len(), 2);
    assert_eq!(calls[0].0, ARTICLE_SQLITE);
    assert_eq!(calls[1].0, "PRAGMA table_info(articles)");

    // Second run on the same (now complete) table: still 0, still no ALTER.
    assert_eq!(migrate::add_missing_columns::<Article, _>(&db).await.unwrap(), 0);
    assert_eq!(db.calls().len(), 3);
}

#[tokio::test]
async fn existing_columns_queries_bind_the_table_name() {
    for (dialect, expected) in [
        (
            Dialect::Postgres,
            "SELECT column_name AS name FROM information_schema.columns \
             WHERE table_schema = current_schema() AND table_name = ?",
        ),
        (
            Dialect::Mysql,
            "SELECT column_name AS name FROM information_schema.columns \
             WHERE table_schema = DATABASE() AND table_name = ?",
        ),
    ] {
        let db = Mock::with_dialect(dialect);
        migrate::add_missing_columns::<Article, _>(&db).await.unwrap();
        let calls = db.calls();
        assert_eq!(calls[0].0, expected);
        assert_eq!(calls[0].1, vec![Value::Text("articles".into())]);
        // No rows => every column is missing => one ALTER per column.
        assert_eq!(calls.len(), 5);
    }
}
