// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//! `bee-rust migrate init` / `bee-rust migrate run`: scaffold a
//! `src/bin/bee_migrate.rs` inside the user's crate and run it through cargo.
//!
//! The CLI never links the user's models and holds no registry: a registry in
//! the CLI process cannot see models living in the user's crate without
//! linking it or parsing its source. `init` writes a small runnable program
//! the user owns and edits once; `run` is a thin `cargo run --bin bee_migrate`
//! with inherited stdio, so build errors land in the terminal unchanged.

use std::fs;
use std::path::Path;
use std::process::Command;

use crate::CliResult;

/// The scaffold, relative to the crate root — also what `run` looks for.
const BIN_PATH: &str = "src/bin/bee_migrate.rs";

/// Write `src/bin/bee_migrate.rs` under `root` (the crate root), creating
/// `src/bin/` if needed.
///
/// Refuses when `root` is not a crate (no `Cargo.toml`) and when the file is
/// already there — user code is never overwritten. `Cargo.toml` itself is not
/// touched: dependencies are the user's file.
pub fn migrate_init(root: &Path) -> CliResult {
    let manifest = root.join("Cargo.toml");
    if !manifest.is_file() {
        return Err(format!(
            "{} not found — run `bee-rust migrate init` from your crate root",
            manifest.display()
        ));
    }
    let bin = root.join(BIN_PATH);
    if bin.exists() {
        return Err(format!("{} already exists; remove it or edit it in place", bin.display()));
    }
    if let Some(parent) = bin.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("failed to create {}: {e}", parent.display()))?;
    }
    fs::write(&bin, SCAFFOLD).map_err(|e| format!("failed to write {}: {e}", bin.display()))?;
    println!("Created {} — edit the TODO lines, then `bee-rust migrate run`.", bin.display());
    Ok(())
}

/// Run the scaffolded binary: `cargo run --bin bee_migrate` in `root`, with
/// inherited stdio. Returns cargo's exit code verbatim, so a failed build or
/// migration reaches the caller's shell with its own status.
pub fn migrate_run(root: &Path) -> Result<i32, String> {
    let bin = root.join(BIN_PATH);
    if !bin.is_file() {
        return Err(format!("{} not found — run `bee-rust migrate init` first", bin.display()));
    }
    let status = Command::new("cargo")
        .args(["run", "--bin", "bee_migrate"])
        .current_dir(root)
        .status()
        .map_err(|e| format!("failed to run `cargo run --bin bee_migrate`: {e}"))?;
    Ok(status.code().unwrap_or(1))
}

/// The program `init` writes: a complete, runnable migration binary whose only
/// blank spots are marked `TODO(you)`. Edited once by the user, then kept in
/// their repository — nothing here is regenerated or overwritten.
const SCAFFOLD: &str = r#"// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
// generated by `bee-rust migrate init`; edit freely.
//
// Add `bee_orm` (with your backend feature) and `tokio` to [dependencies] if
// not already present — `migrate init` wrote only this file.
//
// Run it from your crate root:
//   DATABASE_URL=app.db cargo run --bin bee_migrate
//   DATABASE_URL=postgres://user:pass@host/db cargo run --bin bee_migrate

// TODO(you): your models — declared here or imported from your crate, e.g.
// #[derive(bee_orm::Model, Clone)]
// #[bee(table = "posts")]
// struct Post {
//     #[bee(pk, auto)]
//     id: i64,
//     title: String,
// }

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let dsn = std::env::var("DATABASE_URL").map_err(|_| {
        "DATABASE_URL is not set (a sqlite path like `app.db`, or a postgres:// / mysql:// URL)"
    })?;

    // TODO(you): the pool of your backend — sqlite is the default here:
    let db = bee_orm::pool::sqlite::Pool::connect(&dsn, 4)?;
    // postgres: bee_orm::pool::postgres::Pool::connect(&dsn, 4)?;
    // mysql:    bee_orm::pool::mysql::Pool::connect(&dsn, 4)?;

    // TODO(you): sync the models, parents before children — a table another
    // table references must be created first (foreign keys, and the join
    // tables behind #[bee(m2m(...))]). `sync` creates the table, adds the
    // columns that are missing, and creates each m2m join table. The `_` is
    // the pool type, inferred from `&db`.
    // bee_orm::migrate::sync::<Post, _>(&db).await?;

    println!("migrated");
    Ok(())
}
"#;
