// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//! `migrate init` scaffold logic: file operations only, in temp directories —
//! no cargo invocation, no network. `migrate run` is exercised only on its
//! refusal path here; the real `cargo run` lives in `migrate_e2e.rs`.

use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use bee_cli::{migrate_init, migrate_run};

/// A fresh scratch crate root (with a `Cargo.toml`) under the temp dir.
fn crate_root(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "bee-cli-migrate-{tag}-{}-{}",
        std::process::id(),
        SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()
    ));
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join("Cargo.toml"), "[package]\nname = \"scratch\"\n").unwrap();
    dir
}

#[test]
fn init_creates_the_bin_and_its_parent_directory() {
    let root = crate_root("create");
    migrate_init(&root).unwrap();

    let bin = root.join("src/bin/bee_migrate.rs");
    assert!(bin.is_file(), "{} was not written", bin.display());
    let content = fs::read_to_string(&bin).unwrap();

    // The pinned elements: header + dependency note + entrypoint + DSN.
    assert!(content.contains("generated by `bee-rust migrate init`; edit freely"));
    assert!(content.contains("Add `bee_orm` (with your backend feature) and `tokio`"));
    assert!(content.contains("#[tokio::main]"));
    assert!(content.contains("async fn main() -> Result<(), Box<dyn std::error::Error>>"));
    assert!(content.contains("std::env::var(\"DATABASE_URL\")"));
    // Pool construction with a TODO marker for the chosen backend.
    assert!(content.contains("bee_orm::pool::sqlite::Pool::connect(&dsn, 4)?"));
    assert!(content.contains("TODO(you)"));
    // The ordered sync block and its rule; the `_` is the pool type — the
    // one-argument form `sync::<Post>` does not compile (E0107).
    assert!(content.contains("bee_orm::migrate::sync::<Post, _>(&db).await?;"));
    assert!(content.contains("parents before children"));
    assert!(content.contains("m2m"));
    // `init` never edits the manifest.
    let manifest = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert_eq!(manifest, "[package]\nname = \"scratch\"\n");
    fs::remove_dir_all(&root).unwrap();
}

#[test]
fn init_refuses_to_overwrite_existing_user_code() {
    let root = crate_root("overwrite");
    let bin = root.join("src/bin/bee_migrate.rs");
    fs::create_dir_all(bin.parent().unwrap()).unwrap();
    fs::write(&bin, "// my own migration\n").unwrap();

    let err = migrate_init(&root).unwrap_err();
    assert!(err.contains("already exists; remove it or edit it in place"), "{err}");
    assert_eq!(fs::read_to_string(&bin).unwrap(), "// my own migration\n");
    fs::remove_dir_all(&root).unwrap();
}

#[test]
fn init_refuses_without_a_manifest() {
    let dir = std::env::temp_dir().join(format!(
        "bee-cli-migrate-nomanifest-{}-{}",
        std::process::id(),
        SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()
    ));
    fs::create_dir_all(&dir).unwrap();

    let err = migrate_init(&dir).unwrap_err();
    assert!(err.contains("Cargo.toml not found"), "{err}");
    assert!(!dir.join("src").exists(), "nothing may be created without a crate");
    fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn run_refuses_without_the_scaffold() {
    let root = crate_root("run-missing");
    let err = migrate_run(&root).unwrap_err();
    assert!(err.contains("not found") && err.contains("migrate init` first"), "{err}");
    fs::remove_dir_all(&root).unwrap();
}
