// Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
//! Schema generation for [`Model`] types: `CREATE TABLE IF NOT EXISTS` plus
//! non-destructive `ALTER TABLE ADD COLUMN` (Beego `RunSyncdb` style).
//!
//! Never destructive, by construction: no `DROP`, no type changes, no
//! renames. A renamed field shows up as a missing column and is added; the
//! old column is left alone. Versioned migrations (history table, up/down
//! files) are out of scope.
//!
//! # Dialects
//!
//! DDL differs per backend, so these functions ask the connection: the
//! [`Db::dialect`](crate::Db::dialect) of a pool returns its backend; for
//! mocks and hand-written impls it defaults to `None`, which is a loud error
//! rather than a guess. Column clauses come from
//! [`ColumnDef`](crate::ColumnDef) (derive-generated from the field
//! spellings, or hand-written). The auto-increment primary key is the one
//! structural special case:
//!
//! - sqlite: `INTEGER PRIMARY KEY AUTOINCREMENT` (the only legal inline
//!   form; `BigInt` renders `INTEGER` on sqlite anyway),
//! - postgres: `GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` — `BY DEFAULT`
//!   keeps explicit-id inserts working, matching sqlite/mysql,
//! - mysql: `NOT NULL AUTO_INCREMENT PRIMARY KEY`.
//!
//! # m2m join tables
//!
//! [`create_table`] / [`sync`] also create the join table of every
//! [`Model::m2m`] relation the model declares (`CREATE TABLE IF NOT EXISTS`,
//! composite primary key, reverse `UNIQUE`). [`add_missing_columns`] never
//! touches join tables — they are structural, not column-synced. The join
//! table references both sides, so an m2m **target** model must be synced
//! before the declaring model.
//!
//! # Options
//!
//! The `_with` variants take [`MigrateOptions`] ([`Default`] is the
//! historical behavior). `table_level_fk` is a mysql-only opt-in: the inline
//! `REFERENCES` mysql parses and ignores becomes a table-level
//! `FOREIGN KEY (…)` clause on `CREATE`, and a named
//! `ALTER TABLE … ADD CONSTRAINT {table}_{column}_fk FOREIGN KEY …` on the
//! add path — idempotent by constraint-name lookup, loud over pre-existing
//! orphan rows (the driver's error), and no retrofit of existing columns. On
//! sqlite and postgres, where inline `REFERENCES` is enforced, it is a
//! documented no-op.
//!
//! # Caveats
//!
//! - No identifiers are quoted (rounds-1–3 convention): names come from
//!   macro idents or your own literals.
//! - A missing table seen by `add_missing_columns` alone reports every column
//!   missing, and the first `ALTER` fails with the driver's no-such-table
//!   error ([`sync`] creates the table first).
//! - New `NOT NULL` columns without a default only work on an empty table
//!   (sqlite/postgres reject the `ALTER`, mysql backfills): give the field a
//!   default (`sql_type` with `DEFAULT`, `auto_now*`, `soft_delete`) or make
//!   it `Option<T>`.
//! - No locking: boot-time single-writer use is the assumed deployment.

use crate::{
    ColumnDef, Db, DefaultValue, Dialect, M2mDef, Model, OrmError, Result, SqlType, Value,
};

/// Dials for the migration helpers; [`Default`] is the historical behavior.
#[derive(Debug, Clone, Copy, Default)]
pub struct MigrateOptions {
    /// mysql only: render foreign keys as table-level `FOREIGN KEY (…)`
    /// clauses plus named `ADD CONSTRAINT`s instead of the inline
    /// `REFERENCES` mysql parses and ignores. A no-op on sqlite and postgres,
    /// where inline `REFERENCES` is enforced. Off by default: turning it on
    /// is what makes `ALTER`s fail over pre-existing orphan rows, and it
    /// retrofits nothing — only fresh `CREATE TABLE`s and columns added while
    /// opted in get enforced constraints.
    pub table_level_fk: bool,
}

/// `CREATE TABLE IF NOT EXISTS` with one column clause per
/// [`Model::columns`] entry, in declaration order, plus one join table per
/// [`Model::m2m`] relation this model declares.
///
/// An empty [`columns()`](Model::columns) is a `QueryError` naming the model.
/// Join tables reference both sides, so an m2m **target** model's table must
/// be created first: postgres checks the reference at DDL time and fails
/// loudly, sqlite accepts the dangling DDL and fails at the first `INSERT`.
pub async fn create_table<M: Model, D: Db + ?Sized>(db: &D) -> Result<()> {
    create_table_with::<M, D>(db, MigrateOptions::default()).await
}

/// [`create_table`] with explicit [`MigrateOptions`].
pub async fn create_table_with<M: Model, D: Db + ?Sized>(
    db: &D,
    options: MigrateOptions,
) -> Result<()> {
    let dialect = dialect(db)?;
    let ddl = create_table_sql::<M>(dialect, options)?;
    db.execute(&ddl, &[]).await?;
    for def in M::m2m() {
        let ddl = join_table_sql::<M>(def, dialect, options)?;
        db.execute(&ddl, &[]).await?;
    }
    Ok(())
}

/// Add every column of [`Model::columns`] the table does not have yet: one
/// `ALTER TABLE … ADD COLUMN` per missing column, in declaration order.
///
/// Returns the number of columns added. Never destructive: an existing column
/// of the same name is left untouched (no type changes, no renames, no
/// drops), so a second run adds nothing. m2m join tables are **not** touched
/// — they are created by [`create_table`] / [`sync`] and never column-synced.
pub async fn add_missing_columns<M: Model, D: Db + ?Sized>(db: &D) -> Result<u64> {
    add_missing_columns_with::<M, D>(db, MigrateOptions::default()).await
}

/// [`add_missing_columns`] with explicit [`MigrateOptions`]. Under
/// `table_level_fk` on mysql a missing foreign-key column is added without
/// the inline `REFERENCES` and followed by
/// `ALTER TABLE … ADD CONSTRAINT {table}_{column}_fk FOREIGN KEY …` unless a
/// constraint of that name already exists (checked in
/// `information_schema.table_constraints`) — pre-existing orphan rows make
/// that `ALTER` fail with the driver's error.
pub async fn add_missing_columns_with<M: Model, D: Db + ?Sized>(
    db: &D,
    options: MigrateOptions,
) -> Result<u64> {
    let dialect = dialect(db)?;
    let table_level = dialect == Dialect::Mysql && options.table_level_fk;
    let columns = model_columns::<M>()?;
    let existing = existing_columns::<M, D>(db, dialect).await?;
    let mut affected = 0;
    for column in columns {
        if existing.iter().any(|name| name == column.name) {
            continue;
        }
        let clause =
            if table_level { column_clause(column, dialect) } else { column_sql(column, dialect) };
        let ddl = format!("ALTER TABLE {} ADD COLUMN {clause}", M::table_name());
        affected += db.execute(&ddl, &[]).await?;
        if table_level {
            add_constraint::<M, D>(db, column).await?;
        }
    }
    Ok(affected)
}

/// [`create_table`] then [`add_missing_columns`] — the boot-time call.
/// Returns the number of columns added (0 on a second run).
pub async fn sync<M: Model, D: Db + ?Sized>(db: &D) -> Result<u64> {
    sync_with::<M, D>(db, MigrateOptions::default()).await
}

/// [`sync`] with explicit [`MigrateOptions`].
pub async fn sync_with<M: Model, D: Db + ?Sized>(db: &D, options: MigrateOptions) -> Result<u64> {
    create_table_with::<M, D>(db, options).await?;
    add_missing_columns_with::<M, D>(db, options).await
}

/// The named `FOREIGN KEY` constraint for a just-added column, unless one of
/// that name is already there. Columns without a `#[bee(fk = …)]` reference
/// get nothing.
async fn add_constraint<M: Model, D: Db + ?Sized>(db: &D, column: &ColumnDef) -> Result<()> {
    let Some(reference) = column.references else { return Ok(()) };
    let name = format!("{}_{}_fk", M::table_name(), column.name);
    if constraint_exists(db, M::table_name(), &name).await? {
        return Ok(());
    }
    let ddl = format!(
        "ALTER TABLE {} ADD CONSTRAINT {name} FOREIGN KEY ({}) REFERENCES {} ({})",
        M::table_name(),
        column.name,
        (reference.table)(),
        (reference.pk_column)()
    );
    db.execute(&ddl, &[]).await?;
    Ok(())
}

/// Whether the named foreign-key constraint exists (mysql).
async fn constraint_exists<D: Db + ?Sized>(db: &D, table: &str, name: &str) -> Result<bool> {
    let rows = db
        .query(
            "SELECT constraint_name AS name FROM information_schema.table_constraints \
             WHERE table_schema = DATABASE() AND table_name = ? \
             AND constraint_type = 'FOREIGN KEY' AND constraint_name = ?",
            &[Value::Text(table.into()), Value::Text(name.into())],
        )
        .await?;
    Ok(!rows.is_empty())
}

/// The connection's dialect, or a loud error for impls that do not report one.
fn dialect<D: Db + ?Sized>(db: &D) -> Result<Dialect> {
    db.dialect()
        .ok_or_else(|| OrmError::QueryError("migrate: this Db does not report a dialect".into()))
}

fn model_columns<M: Model + ?Sized>() -> Result<&'static [ColumnDef]> {
    let columns = M::columns();
    if columns.is_empty() {
        return Err(OrmError::QueryError(format!(
            "migrate: `{}` has no columns(); implement Model::columns() to use migrations",
            M::table_name()
        )));
    }
    Ok(columns)
}

fn create_table_sql<M: Model + ?Sized>(
    dialect: Dialect,
    options: MigrateOptions,
) -> Result<String> {
    let columns = model_columns::<M>()?;
    let table_level = dialect == Dialect::Mysql && options.table_level_fk;
    let mut clauses: Vec<String> =
        columns
            .iter()
            .map(|column| {
                if table_level {
                    column_clause(column, dialect)
                } else {
                    column_sql(column, dialect)
                }
            })
            .collect();
    if table_level {
        clauses.extend(columns.iter().filter_map(table_level_fk));
    }
    Ok(format!("CREATE TABLE IF NOT EXISTS {} ({})", M::table_name(), clauses.join(", ")))
}

/// The join table of one m2m relation: both sides' primary-key columns,
/// `NOT NULL`, a composite `PRIMARY KEY` (kills duplicate pairs) and the
/// reverse `UNIQUE` (the other direction's index) — one portable statement,
/// so there is no `CREATE INDEX IF NOT EXISTS` idempotency problem (mysql
/// has none). Under mysql's `table_level_fk` the two `REFERENCES` clauses
/// move to the table body like any other table's.
fn join_table_sql<M: Model + ?Sized>(
    def: &M2mDef,
    dialect: Dialect,
    options: MigrateOptions,
) -> Result<String> {
    let local = local_pk_column::<M>()?;
    let target_table = (def.target_table)();
    let target =
        (def.target_columns)().iter().find(|column| column.primary_key).ok_or_else(|| {
            OrmError::QueryError(format!(
                "migrate: `{target_table}` has no primary-key column in its columns() \
                 metadata (m2m target of `{}`)",
                M::table_name()
            ))
        })?;
    let table_level = dialect == Dialect::Mysql && options.table_level_fk;
    let side = |name: &str, sql: SqlType, table: &str, pk: &str| {
        let base = format!("{name} {} NOT NULL", sql_type(sql, dialect));
        if table_level { base } else { format!("{base} REFERENCES {table} ({pk})") }
    };
    let mut clauses = vec![
        side(def.local_column, local.sql, M::table_name(), local.name),
        side(def.foreign_column, target.sql, target_table, target.name),
    ];
    if table_level {
        clauses.push(format!(
            "FOREIGN KEY ({}) REFERENCES {} ({})",
            def.local_column,
            M::table_name(),
            local.name
        ));
        clauses.push(format!(
            "FOREIGN KEY ({}) REFERENCES {target_table} ({})",
            def.foreign_column, target.name
        ));
    }
    clauses.push(format!("PRIMARY KEY ({}, {})", def.local_column, def.foreign_column));
    clauses.push(format!("UNIQUE ({}, {})", def.foreign_column, def.local_column));
    Ok(format!("CREATE TABLE IF NOT EXISTS {} ({})", def.table, clauses.join(", ")))
}

/// `M`'s primary-key column metadata — the join table takes its type.
fn local_pk_column<M: Model + ?Sized>() -> Result<&'static ColumnDef> {
    model_columns::<M>()?.iter().find(|column| column.name == M::pk_column()).ok_or_else(|| {
        OrmError::QueryError(format!(
            "migrate: `{}` has no column metadata for its primary key `{}`",
            M::table_name(),
            M::pk_column()
        ))
    })
}

/// `FOREIGN KEY (col) REFERENCES t (pk)` for a column that has one.
fn table_level_fk(column: &ColumnDef) -> Option<String> {
    let reference = column.references?;
    Some(format!(
        "FOREIGN KEY ({}) REFERENCES {} ({})",
        column.name,
        (reference.table)(),
        (reference.pk_column)()
    ))
}

/// `<name> <type> [NOT NULL] [DEFAULT <v>] [PRIMARY KEY] [REFERENCES …]`,
/// with the auto-increment spellings of the module docs.
fn column_sql(column: &ColumnDef, dialect: Dialect) -> String {
    let mut clause = column_clause(column, dialect);
    if let Some(reference) = column.references {
        clause.push_str(" REFERENCES ");
        clause.push_str((reference.table)());
        clause.push_str(" (");
        clause.push_str((reference.pk_column)());
        clause.push(')');
    }
    clause
}

/// [`column_sql`] without the `REFERENCES` tail — what mysql's table-level
/// opt-in renders (the constraint moves to the table body / an `ALTER`).
fn column_clause(column: &ColumnDef, dialect: Dialect) -> String {
    let mut clause = format!("{} {}", column.name, sql_type(column.sql, dialect));
    if column.primary_key && column.auto_increment {
        match dialect {
            Dialect::Sqlite => clause.push_str(" PRIMARY KEY AUTOINCREMENT"),
            Dialect::Postgres => {
                clause.push_str(" GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
            }
            Dialect::Mysql => clause.push_str(" NOT NULL AUTO_INCREMENT PRIMARY KEY"),
        }
    } else {
        if !column.nullable {
            clause.push_str(" NOT NULL");
        }
        if let Some(default) = column.default {
            clause.push_str(" DEFAULT ");
            clause.push_str(&default_sql(default, dialect));
        }
        if column.primary_key {
            clause.push_str(" PRIMARY KEY");
        }
    }
    clause
}

fn sql_type(sql: SqlType, dialect: Dialect) -> &'static str {
    match sql {
        SqlType::Raw(raw) => raw,
        SqlType::Int => match dialect {
            Dialect::Mysql => "INT",
            Dialect::Sqlite | Dialect::Postgres => "INTEGER",
        },
        SqlType::BigInt => match dialect {
            Dialect::Sqlite => "INTEGER",
            Dialect::Postgres | Dialect::Mysql => "BIGINT",
        },
        SqlType::Real => match dialect {
            Dialect::Mysql => "FLOAT",
            Dialect::Sqlite | Dialect::Postgres => "REAL",
        },
        SqlType::Double => match dialect {
            Dialect::Sqlite => "REAL",
            Dialect::Postgres => "DOUBLE PRECISION",
            Dialect::Mysql => "DOUBLE",
        },
        SqlType::Bool => match dialect {
            Dialect::Sqlite => "INTEGER",
            Dialect::Postgres | Dialect::Mysql => "BOOLEAN",
        },
        SqlType::Text => "TEXT",
        SqlType::Blob => match dialect {
            Dialect::Postgres => "BYTEA",
            Dialect::Sqlite | Dialect::Mysql => "BLOB",
        },
        SqlType::Json => match dialect {
            Dialect::Postgres => "JSONB",
            Dialect::Sqlite => "TEXT",
            Dialect::Mysql => "JSON",
        },
        // sqlite stores the date/time/decimal types as text — a `DECIMAL`
        // declaration would get NUMERIC affinity and turn `"1.50"` into the
        // `REAL` 1.5, so `TEXT` everywhere here.
        SqlType::Date => match dialect {
            Dialect::Sqlite => "TEXT",
            Dialect::Postgres => "date",
            Dialect::Mysql => "date",
        },
        SqlType::DateTime => match dialect {
            Dialect::Sqlite => "TEXT",
            Dialect::Postgres => "timestamp",
            Dialect::Mysql => "datetime(6)",
        },
        SqlType::DateTimeTz => match dialect {
            Dialect::Sqlite => "TEXT",
            Dialect::Postgres => "timestamptz",
            Dialect::Mysql => "timestamp(6)",
        },
        SqlType::Decimal => match dialect {
            Dialect::Sqlite => "TEXT",
            Dialect::Postgres => "numeric",
            Dialect::Mysql => "decimal(65,30)",
        },
    }
}

fn default_sql(default: DefaultValue, dialect: Dialect) -> String {
    match default {
        DefaultValue::Int(value) => value.to_string(),
        DefaultValue::Raw(raw) => raw.to_string(),
        DefaultValue::Bool(value) => match dialect {
            Dialect::Postgres => if value { "true" } else { "false" }.to_string(),
            Dialect::Sqlite | Dialect::Mysql => i64::from(value).to_string(),
        },
    }
}

/// The table's current column names, read per dialect and keyed uniformly as
/// `name` (the `information_schema` queries alias explicitly).
async fn existing_columns<M: Model + ?Sized, D: Db + ?Sized>(
    db: &D,
    dialect: Dialect,
) -> Result<Vec<String>> {
    let table = M::table_name();
    let (sql, params): (String, Vec<Value>) = match dialect {
        Dialect::Sqlite => (format!("PRAGMA table_info({table})"), Vec::new()),
        Dialect::Postgres => (
            "SELECT column_name AS name FROM information_schema.columns \
             WHERE table_schema = current_schema() AND table_name = ?"
                .into(),
            vec![Value::Text(table.into())],
        ),
        Dialect::Mysql => (
            "SELECT column_name AS name FROM information_schema.columns \
             WHERE table_schema = DATABASE() AND table_name = ?"
                .into(),
            vec![Value::Text(table.into())],
        ),
    };
    let rows = db.query(&sql, &params).await?;
    Ok(rows
        .iter()
        .filter_map(|row| row.get("name").and_then(serde_json::Value::as_str).map(str::to_owned))
        .collect())
}
